[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  PNPM_FLAGS = "--shamefully-hoist"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "pnpm dev"
  targetPort = 3000
  port = 8888
